variables:
  PathToSolution: 'DiscordSocialSDKWrapper.sln'
  PathToSocialSdkProject: 'src/Discord.SocialSdk/Discord.SocialSdk.csproj'
  DotnetSdkVersion: '9.x'
  BuildConfiguration: 'Release'

trigger:
  branches:
    include:
      - master
  paths:
    exclude:
    - README.md

pr:
  autoCancel: true
  branches:
    include:
      - '*'
  paths:
    exclude:
    - README.md

jobs:
  - job: Build
    strategy:
      matrix:
        windows:
          image: 'windows-2022'
        linux:
          image: 'ubuntu-24.04'
        macOS:
          image: 'macOS-14'
    pool:
      vmImage: $(image)
    displayName: Build Library
    steps:
      - task: UseDotNet@2
        displayName: Install .NET SDK
        inputs:
          packageType: sdk
          version: $(DotnetSdkVersion)
      - task: CmdLine@2
        displayName: Build Solution
        inputs:
          script: 'dotnet build $(PathToSocialSdkProject) --configuration $(BuildConfiguration) --verbosity normal'
      - task: CmdLine@2
        displayName: Run Tests
        inputs:
          script: 'dotnet test $(PathToSolution) --configuration $(BuildConfiguration) --verbosity normal'